
services:
  novnc:  
    build:
        context: .
        dockerfile: Dockerfile

    image: novnc-service:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=600
      - DISPLAY_HEIGHT=600
      - RUN_XTERM=no

    ports:
      - 6080 
      - 5900
    
    labels:
      caddy: novnc.do.jointheleague.org
      caddy.handle_path.@ws.0_header: Connection *Upgrade*
      caddy.handle_path.@ws.1_header: Upgrade websocket
      caddy.handle_path.0_reverse_proxy: "@ws {{upstreams 6080}}"
      caddy.handle_path.1_reverse_proxy: "{{upstreams 6080}}"

    networks:
      - x11
      - caddy 

networks:
  x11:
    internal: true
  caddy:
    external: true
